
name: Run Test

on: 
  pull_request:
    types: [opened,synchronize]
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: File tree
      run: tree

    - name: Install Boost
      run: sudo apt install -y libboost-all-dev

    - name: Install Google Test
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        make
        cd ../
        sudo cp -r ./googlemock/include/gmock /usr/local/include/gmock
        sudo cp -r ./googletest/include/gtest /usr/local/include/gtest
        sudo cp ./build/lib/*.a /usr/local/lib/
        cd ../

    - name: Install Algo.cpp
      run: |
        cd test
        git clone https://github.com/algocpp/algocpp --recursive
    
    - name: Build Test Code
      run: |
        cd test
        mkdir build
        cd build
        cmake ..
        make
    
    - name: Run Tests
      run: |
        cd test/build
        ./palind
